const billingApi = (path, options = {}) => window.SoftwareAuth.request(path, options);
const billingEscape = (value) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const amount = (value, currency = "usd") => new Intl.NumberFormat(undefined, { style: "currency", currency: String(currency).toUpperCase() }).format(Number(value || 0) / 100);
const limitText = (value) => value === null || value === undefined ? "Unlimited" : Number(value).toLocaleString();
function billingMessage(text, kind = "success") { const node = document.getElementById("billing-message"); node.textContent = text; node.className = `message visible ${kind}`; }
function usageRow(label, used, limit, suffix = "") { const unlimited = limit === null || limit === undefined; const percent = unlimited ? 0 : Math.min(100, Number(used || 0) / Math.max(1, Number(limit)) * 100); return `<div class="usage-row"><div><strong>${billingEscape(label)}</strong><span>${Number(used || 0).toLocaleString()} / ${unlimited ? "Unlimited" : Number(limit).toLocaleString()} ${billingEscape(suffix)}</span></div><div class="usage-track"><i style="width:${percent}%"></i></div></div>`; }
async function loadBilling() {
  try {
    const [mine, catalog] = await Promise.all([billingApi("/api/billing/me"), billingApi("/api/billing/plans")]); const b = mine.billing; const p = b.plan; const s = b.subscription; const u = b.usage;
    document.getElementById("billing-plan").textContent = p.name || "Free"; document.getElementById("billing-price").textContent = p.price || "Configurable"; document.getElementById("billing-period").textContent = `${s.status} · ${new Date(s.current_period_start).toLocaleDateString()} – ${new Date(s.current_period_end).toLocaleDateString()}`; document.getElementById("usage-period").textContent = `Billing period ends ${new Date(s.current_period_end).toLocaleDateString()}`;
    document.getElementById("payment-method").innerHTML = b.stripe?.customer_id ? `<p>Payment details are securely managed by the billing provider.</p><button id="open-provider" class="secondary">Open billing portal</button>` : `<p>No payment method is required for the ${billingEscape(p.name)} plan.</p>`;
    document.getElementById("billing-usage").innerHTML = usageRow("Projects", u.projects, p.max_projects) + usageRow("Workflows", u.workflows, p.monthly_workflow_limit) + usageRow("Telemetry events", u.telemetry_events, p.monthly_telemetry_limit) + usageRow("Connected installations", u.installations, p.max_installations) + usageRow("Team members", u.team_members, p.max_team_members) + usageRow("Data retention", p.retention_days || 0, p.retention_days, "days");
    document.getElementById("plan-grid").innerHTML = catalog.plans.map((plan) => `<article class="plan-card ${plan.id === p.id ? "selected" : ""}"><header><div><h3>${billingEscape(plan.name)}</h3><p>${billingEscape(plan.audience)}</p></div>${plan.id === p.id ? '<span class="current-chip">Current</span>' : ""}</header><strong class="plan-price">${billingEscape(plan.price)}</strong><ul><li>${limitText(plan.max_projects)} projects</li><li>${limitText(plan.monthly_workflow_limit)} workflows / month</li><li>${limitText(plan.monthly_telemetry_limit)} telemetry events</li><li>${limitText(plan.max_team_members)} team members</li><li>${limitText(plan.max_installations)} installations</li><li>${plan.retention_days ? `${plan.retention_days} day retention` : "Custom retention"}</li><li>${plan.features?.advanced_guardrails ? "Advanced guardrails" : "Standard guardrails"}</li><li>${plan.features?.human_intervention_history ? "Human intervention history" : "Core reliability history"}</li></ul>${plan.id === p.id ? '<button disabled>Current plan</button>' : plan.id === "enterprise" ? '<a class="button secondary" href="/request-access">Contact sales</a>' : `<button data-plan-id="${billingEscape(plan.id)}">Upgrade plan</button>`}</article>`).join("");
    document.getElementById("invoice-table").innerHTML = b.invoices?.length ? b.invoices.map((invoice) => `<tr><td>${new Date(invoice.created_at).toLocaleDateString()}</td><td>${amount(invoice.amount_paid || invoice.amount_due, invoice.currency)}</td><td>${billingEscape(invoice.plan_name || p.name)}</td><td>${billingEscape(invoice.status || "pending")}</td><td>${billingEscape(invoice.stripe_invoice_id)}</td><td>${invoice.hosted_invoice_url ? `<a href="${billingEscape(invoice.hosted_invoice_url)}" rel="noopener">View invoice</a>` : "Unavailable"}</td></tr>`).join("") : '<tr><td colspan="6"><div class="empty-state compact"><p>No billing history yet.</p></div></td></tr>';
    document.getElementById("open-provider")?.addEventListener("click", openPortal);
  } catch (error) { billingMessage(error.message, "error"); document.getElementById("invoice-table").innerHTML = '<tr><td colspan="6">Billing could not be loaded. Retry this page.</td></tr>'; }
}
async function openPortal() { try { const response = await billingApi("/api/billing/portal", { method: "POST", body: "{}" }); if (response.portal_url) location.href = response.portal_url; } catch (error) { billingMessage(error.message, "error"); } }
document.addEventListener("click", async (event) => { const button = event.target.closest("[data-plan-id]"); if (!button) return; try { button.disabled = true; const response = await billingApi("/api/billing/checkout", { method: "POST", body: JSON.stringify({ plan_id: button.dataset.planId, success_url: `${location.origin}/billing?checkout=success`, cancel_url: `${location.origin}/billing?checkout=cancelled` }) }); if (response.checkout_url) location.href = response.checkout_url; else { billingMessage(response.message || "Plan updated."); await loadBilling(); } } catch (error) { billingMessage(error.message, "error"); button.disabled = false; } });
document.getElementById("manage-subscription").addEventListener("click", openPortal);
document.addEventListener("DOMContentLoaded", async () => { try { await window.SoftwareAuth.session(); await loadBilling(); } catch (_) { location.href = `/login?next=${encodeURIComponent(location.pathname)}`; } });
