const detailApi = (path, options = {}) => window.SoftwareAuth.request(path, options);
const detailEscape = (value) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const detailDate = (value) => value ? new Date(value).toLocaleString() : "No activity yet";
const projectId = decodeURIComponent(location.pathname.split("/").filter(Boolean).pop() || "");
function detailEmpty(message) { return `<div class="empty-state compact"><p>${detailEscape(message)}</p></div>`; }
function setDetail(id, value) { const node = document.getElementById(id); if (node) node.textContent = value; }
async function loadProjectDetail() {
  try {
    const data = await detailApi(`/api/projects/${encodeURIComponent(projectId)}`); const p = data.project; const usage = data.usage || {};
    setDetail("detail-name", p.name); setDetail("detail-id", p.id); setDetail("detail-status", String(p.status).toUpperCase()); document.getElementById("detail-status").className = `status-badge status-${p.status}`;
    setDetail("detail-meta", `${p.environment} · Created ${detailDate(p.created_at)} · Last activity ${detailDate(p.last_activity_at)}`); document.getElementById("connect-project").href = `/api-keys?project=${encodeURIComponent(p.id)}`;
    setDetail("metric-reliability", `${Number(p.reliability_score || 0).toFixed(1)}%`); setDetail("metric-workflows", p.workflow_count || 0); setDetail("metric-failures", data.summary.failures || 0); setDetail("metric-installations", p.connected_installation_count || 0); setDetail("metric-models", usage.model_call || 0); setDetail("metric-tools", usage.tool_call || 0);
    const workflows = data.workflows || []; document.getElementById("detail-workflows").innerHTML = workflows.length ? workflows.map((w) => `<tr><td><strong>${detailEscape(w.workflow_name)}</strong><small>${detailEscape(w.workflow_id)}</small></td><td><span class="status-badge status-${w.success === 0 ? "disconnected" : "connected"}">${detailEscape(w.status)}</span></td><td>${detailEscape(w.session_id || w.app_user_id || "Not provided")}</td><td>${Number(w.reliability_score || 0).toFixed(1)}%</td><td>${Number(w.total_latency_ms || 0)} ms</td><td>${Number(w.model_calls || 0)} model · ${Number(w.tool_calls || 0)} tool</td><td>${detailDate(w.started_at)}</td></tr>`).join("") : `<tr><td colspan="7">No workflows have been recorded for this project yet.</td></tr>`;
    const installations = data.installations || []; document.getElementById("detail-installations").innerHTML = installations.length ? installations.map((i) => `<article class="device-card"><div><span class="status-badge status-${detailEscape(i.status)}">${detailEscape(i.status)}</span><h3>${detailEscape(i.device_label)}</h3><p>${detailEscape(i.operating_system || "Unknown OS")} · ${detailEscape(i.runtime || "Unknown runtime")} · ${detailEscape(i.environment)}</p></div><p class="muted">Last seen ${detailDate(i.last_seen_at)}</p></article>`).join("") : detailEmpty("No installations are connected to this project yet.");
    const sessions = data.sessions || []; document.getElementById("detail-sessions").innerHTML = sessions.length ? sessions.map((s) => `<article class="device-card"><div><h3>${detailEscape(s.session_id)}</h3><p>${detailEscape(s.app_user_id || "No app user identifier")}</p></div><p>${s.workflow_count} workflows · ${detailDate(s.last_seen_at)}</p></article>`).join("") : detailEmpty("No sessions have been recorded for this project yet.");
    setDetail("detail-failures", data.summary.failures ? `${data.summary.failures} failed workflows are linked to this project.` : "No failures have been recorded for this project yet."); setDetail("detail-guardrails", workflows.some((w) => w.guardrail_actions) ? "Guardrail actions are available in workflow history." : "No guardrail actions have been recorded for this project yet.");
    document.getElementById("detail-usage").innerHTML = ["workflow", "telemetry_event", "model_call", "tool_call", "api_request"].map((key) => `<div><span>${key.replaceAll("_", " ")}</span><strong>${Number(usage[key] || 0).toLocaleString()}</strong></div>`).join(""); document.querySelector("#project-settings [name=name]").value = p.name; document.querySelector("#project-settings [name=environment]").value = p.environment;
  } catch (error) { document.querySelector("main").innerHTML = `<div class="empty-state"><h1>Project unavailable</h1><p>${detailEscape(error.message)}</p><a class="button" href="/projects">Back to projects</a></div>`; }
}
document.addEventListener("DOMContentLoaded", async () => { try { await window.SoftwareAuth.session(); } catch (_) { location.href = `/login?next=${encodeURIComponent(location.pathname)}`; return; } document.getElementById("make-current").addEventListener("click", async () => { await detailApi("/api/projects/current", { method: "POST", body: JSON.stringify({ project_id: projectId }) }); setDetail("detail-message", "Current project updated."); document.getElementById("detail-message").className = "message visible success"; }); document.getElementById("project-settings").addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; await detailApi(`/api/projects/${encodeURIComponent(projectId)}`, { method: "PATCH", body: JSON.stringify({ name: form.name.value, environment: form.environment.value }) }); await loadProjectDetail(); }); await loadProjectDetail(); });
