from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, List, Optional

from matrixs.config import MATRIXS_DIR_NAME, project_config_path, project_env_path, read_json

from .models import Credentials, IntegrationPlan, PlanChange, ProjectAnalysis


RUNTIME_BOOTSTRAP = """from matrixs.runtime.instrumentation import activate_from_environment

activate_from_environment()
"""


def _bytes(value: str) -> bytes:
    return value.encode("utf-8")


def _current_bytes(path: Path) -> Optional[bytes]:
    try:
        return path.read_bytes() if path.exists() else None
    except OSError:
        return None


def _change(path: Path, content: str, *, sensitive: bool = False) -> Optional[PlanChange]:
    encoded = _bytes(content)
    current = _current_bytes(path)
    if current == encoded:
        return None
    return PlanChange(
        path=path,
        content=encoded,
        action="update" if current is not None else "create",
        sensitive=sensitive,
    )


def _updated_gitignore(path: Path) -> str:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    existing = set(current.splitlines())
    additions = [
        ".matrixs/.env",
        ".matrixs/backups/",
    ]
    missing = [line for line in additions if line not in existing]
    if not missing:
        return current
    prefix = current
    if prefix and not prefix.endswith("\n"):
        prefix += "\n"
    if prefix and not prefix.endswith("\n\n"):
        prefix += "\n"
    return prefix + "# Matrixs local integration\n" + "\n".join(missing) + "\n"


def _dotenv(credentials: Credentials) -> str:
    return (
        "# Generated by Matrixs. Do not commit this file.\n"
        f"MATRIXS_PROJECT_ID={credentials.project_id}\n"
        f"MATRIXS_API_KEY={credentials.api_key}\n"
        f"MATRIXS_API_URL={credentials.api_url}\n"
        f"MATRIXS_PROJECT_NAME={credentials.project_name}\n"
        f"MATRIXS_INSTALLATION_ID={credentials.installation_id}\n"
    )


def build_integration_plan(
    analysis: ProjectAnalysis,
    credentials: Credentials,
    *,
    backup_id: str,
    connected_at: Optional[str] = None,
) -> IntegrationPlan:
    root = analysis.path.resolve()
    existing_config = read_json(project_config_path(root))
    integration_backup_id = str(existing_config.get("integration_backup") or backup_id)
    config = {
        "adapters": analysis.adapters,
        "ai_libraries": analysis.ai_libraries,
        "api_url": credentials.api_url,
        "auto_instrument": True,
        "connected_at": connected_at or datetime.now(timezone.utc).isoformat(),
        "deployment_files": analysis.deployment_files,
        "framework": analysis.framework,
        "integration_backup": integration_backup_id,
        "integration_version": 1,
        "installation_id": credentials.installation_id,
        "project_id": credentials.project_id,
        "project_name": credentials.project_name,
        "run_command": ["matrixs", "run"],
        "runtime": analysis.runtime,
        "startup_command": analysis.startup_command,
    }
    candidate_changes: Iterable[Optional[PlanChange]] = (
        _change(project_config_path(root), json.dumps(config, indent=2, sort_keys=True) + "\n"),
        _change(project_env_path(root), _dotenv(credentials), sensitive=True),
        _change(root / MATRIXS_DIR_NAME / "runtime" / "sitecustomize.py", RUNTIME_BOOTSTRAP),
        _change(root / ".gitignore", _updated_gitignore(root / ".gitignore")),
    )
    changes: List[PlanChange] = [change for change in candidate_changes if change is not None]
    return IntegrationPlan(
        project_root=root,
        analysis=analysis,
        credentials=credentials,
        backup_id=backup_id,
        integration_backup_id=integration_backup_id,
        changes=changes,
        metadata={"config": config},
    )
